<?xml version="1.0" encoding="utf-8"?><Database Name="HighchartsSampleDb" Class="DbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=HighchartsSampleDb;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HighchartsSampleDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[Values]" Member="Values">
    <Type Name="Value">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Member="Value1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Datetime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>